const GET_DOGS = "GET_DOGS";
const GET_TEMPERAMENTS = "GET_TEMPERAMENTS";
const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
const CREATE_DOG = "CREATE_DOG";
const FILTER_TEMPERAMENTS = "FILTER_TEMPERAMENTS";

module.exports = {
    GET_DOGS,
    GET_TEMPERAMENTS,
    SET_CURRENT_PAGE,
    CREATE_DOG,
    FILTER_TEMPERAMENTS,
}