const GET_DOGS = "GET_DOGS";
const GET_TEMPERAMENTS = "GET_TEMPERAMENTS";
const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
const CREATE_DOG = "CREATE_DOG";
const FILTER_TEMPERAMENTS = "FILTER_TEMPERAMENTS";
const DISPLAY_STATE = "DISPLAY_STATE";
const GET_DOGS_API = "GET_DOGS_API";
const GET_DOGS_CREATE = "GET_DOGS_CREATE";
const RESET_FILTERS = "RESET_FILTERS";
const FILTER_WEIGHT = "FILTER_WEIGHT";
const FILTER_ALPHABETIC = "FILTER_ALPHABETIC";
const GET_BY_NAME = "GET_BY_NAME";
const GET_DOG_BY_ID = "GET_DOG_BY_ID";
const REST_BY_ID = "REST_BY_ID ";

module.exports = {
    GET_DOGS,
    GET_TEMPERAMENTS,
    SET_CURRENT_PAGE,
    CREATE_DOG,
    FILTER_TEMPERAMENTS,
    DISPLAY_STATE,
    GET_DOGS_API,
    GET_DOGS_CREATE,
    RESET_FILTERS,
    FILTER_WEIGHT,
    FILTER_ALPHABETIC,
    GET_BY_NAME,
    GET_DOG_BY_ID,
    REST_BY_ID
}